# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/ZYNQ_Mizar-7020/06_Linux_Demo/6_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_v_axi4s_vid_out_0_0/hdmi_out_v_axi4s_vid_out_0_0.xci
# IP: The module: 'hdmi_out_v_axi4s_vid_out_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ZYNQ_Mizar-7020/06_Linux_Demo/6_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_v_axi4s_vid_out_0_0/hdmi_out_v_axi4s_vid_out_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_out_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/ZYNQ_Mizar-7020/06_Linux_Demo/6_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_v_axi4s_vid_out_0_0/hdmi_out_v_axi4s_vid_out_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_out_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/ZYNQ_Mizar-7020/06_Linux_Demo/6_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_v_axi4s_vid_out_0_0/hdmi_out_v_axi4s_vid_out_0_0.xci
# IP: The module: 'hdmi_out_v_axi4s_vid_out_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ZYNQ_Mizar-7020/06_Linux_Demo/6_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_v_axi4s_vid_out_0_0/hdmi_out_v_axi4s_vid_out_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_out_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/ZYNQ_Mizar-7020/06_Linux_Demo/6_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_v_axi4s_vid_out_0_0/hdmi_out_v_axi4s_vid_out_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_out_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
