# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/hdmi_out_axi_smc_0.xci
# IP: The module: 'hdmi_out_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/bd_173e.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_0/bd_173e_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_1/bd_173e_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_2/bd_173e_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_3/bd_173e_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_4/bd_173e_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_5/bd_173e_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_6/bd_173e_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_7/bd_173e_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_8/bd_173e_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_9/bd_173e_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_out_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_1/bd_173e_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_1/bd_173e_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_5/bd_173e_s00a2s_0_ooc.xdc

# XDC: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_6/bd_173e_sarn_0_ooc.xdc

# XDC: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_7/bd_173e_srn_0_ooc.xdc

# XDC: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_8/bd_173e_m00s2a_0_ooc.xdc

# IP: D:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/hdmi_out_axi_smc_0.xci
# IP: The module: 'hdmi_out_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/bd_173e.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_0/bd_173e_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_1/bd_173e_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_2/bd_173e_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_3/bd_173e_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_4/bd_173e_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_5/bd_173e_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_6/bd_173e_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_7/bd_173e_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_8/bd_173e_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_9/bd_173e_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_out_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_1/bd_173e_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_1/bd_173e_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_5/bd_173e_s00a2s_0_ooc.xdc

# XDC: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_6/bd_173e_sarn_0_ooc.xdc

# XDC: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_7/bd_173e_srn_0_ooc.xdc

# XDC: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_8/bd_173e_m00s2a_0_ooc.xdc
