# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/hdmi_out.xdc

# Block Designs: bd/hdmi_out/hdmi_out.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out || ORIG_REF_NAME==hdmi_out} -quiet] -quiet

# IP: bd/hdmi_out/ip/hdmi_out_processing_system7_0_0/hdmi_out_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_processing_system7_0_0 || ORIG_REF_NAME==hdmi_out_processing_system7_0_0} -quiet] -quiet

# IP: bd/hdmi_out/ip/hdmi_out_axi_vdma_0_0/hdmi_out_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_axi_vdma_0_0 || ORIG_REF_NAME==hdmi_out_axi_vdma_0_0} -quiet] -quiet

# IP: bd/hdmi_out/ip/hdmi_out_axi_smc_0/hdmi_out_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_axi_smc_0 || ORIG_REF_NAME==hdmi_out_axi_smc_0} -quiet] -quiet

# IP: bd/hdmi_out/ip/hdmi_out_rst_ps7_0_140M_0/hdmi_out_rst_ps7_0_140M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_rst_ps7_0_140M_0 || ORIG_REF_NAME==hdmi_out_rst_ps7_0_140M_0} -quiet] -quiet

# IP: bd/hdmi_out/ip/hdmi_out_xbar_0/hdmi_out_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_xbar_0 || ORIG_REF_NAME==hdmi_out_xbar_0} -quiet] -quiet

# IP: bd/hdmi_out/ip/hdmi_out_ps7_0_axi_periph_0/hdmi_out_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_ps7_0_axi_periph_0 || ORIG_REF_NAME==hdmi_out_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/hdmi_out/ip/hdmi_out_rst_ps7_0_100M_0/hdmi_out_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_rst_ps7_0_100M_0 || ORIG_REF_NAME==hdmi_out_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/hdmi_out/ip/hdmi_out_v_axi4s_vid_out_0_0/hdmi_out_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==hdmi_out_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/hdmi_out/ip/hdmi_out_v_tc_0_0/hdmi_out_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_v_tc_0_0 || ORIG_REF_NAME==hdmi_out_v_tc_0_0} -quiet] -quiet

# IP: bd/hdmi_out/ip/hdmi_out_rgb2dvi_0_1/hdmi_out_rgb2dvi_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_rgb2dvi_0_1 || ORIG_REF_NAME==hdmi_out_rgb2dvi_0_1} -quiet] -quiet

# IP: bd/hdmi_out/ip/hdmi_out_axi_dynclk_0_0/hdmi_out_axi_dynclk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_axi_dynclk_0_0 || ORIG_REF_NAME==hdmi_out_axi_dynclk_0_0} -quiet] -quiet

# IP: bd/hdmi_out/ip/hdmi_out_xlconstant_1_0/hdmi_out_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_xlconstant_1_0 || ORIG_REF_NAME==hdmi_out_xlconstant_1_0} -quiet] -quiet

# IP: bd/hdmi_out/ip/hdmi_out_xlconcat_0_0/hdmi_out_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_xlconcat_0_0 || ORIG_REF_NAME==hdmi_out_xlconcat_0_0} -quiet] -quiet

# IP: bd/hdmi_out/ip/hdmi_out_auto_pc_0/hdmi_out_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_auto_pc_0 || ORIG_REF_NAME==hdmi_out_auto_pc_0} -quiet] -quiet

# XDC: bd/hdmi_out/hdmi_out_ooc.xdc
