# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Mizar_Z7020_2018.3/Part4_Linux_Demo/10_petalinux_hdmi_wifi/petalinux_hdmi/petalinux_hdmi.cache/wt [current_project]
set_property parent.project_path D:/Mizar_Z7020_2018.3/Part4_Linux_Demo/10_petalinux_hdmi_wifi/petalinux_hdmi/petalinux_hdmi.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths d:/Mizar_Z7020_2018.3/Part4_Linux_Demo/10_petalinux_hdmi_wifi/petalinux_hdmi/repo [current_project]
update_ip_catalog
set_property ip_output_repo d:/Mizar_Z7020_2018.3/Part4_Linux_Demo/10_petalinux_hdmi_wifi/petalinux_hdmi/petalinux_hdmi.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/Mizar_Z7020_2018.3/Part4_Linux_Demo/10_petalinux_hdmi_wifi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/hdl/hdmi_out_wrapper.v
add_files D:/Mizar_Z7020_2018.3/Part4_Linux_Demo/10_petalinux_hdmi_wifi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/hdmi_out.bd
set_property used_in_implementation false [get_files -all d:/Mizar_Z7020_2018.3/Part4_Linux_Demo/10_petalinux_hdmi_wifi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_processing_system7_0_0/hdmi_out_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Mizar_Z7020_2018.3/Part4_Linux_Demo/10_petalinux_hdmi_wifi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_vdma_0_0/hdmi_out_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Mizar_Z7020_2018.3/Part4_Linux_Demo/10_petalinux_hdmi_wifi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_vdma_0_0/hdmi_out_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Mizar_Z7020_2018.3/Part4_Linux_Demo/10_petalinux_hdmi_wifi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_vdma_0_0/hdmi_out_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Mizar_Z7020_2018.3/Part4_Linux_Demo/10_petalinux_hdmi_wifi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Mizar_Z7020_2018.3/Part4_Linux_Demo/10_petalinux_hdmi_wifi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_1/bd_173e_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Mizar_Z7020_2018.3/Part4_Linux_Demo/10_petalinux_hdmi_wifi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_1/bd_173e_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all d:/Mizar_Z7020_2018.3/Part4_Linux_Demo/10_petalinux_hdmi_wifi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_5/bd_173e_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Mizar_Z7020_2018.3/Part4_Linux_Demo/10_petalinux_hdmi_wifi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_6/bd_173e_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Mizar_Z7020_2018.3/Part4_Linux_Demo/10_petalinux_hdmi_wifi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_7/bd_173e_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Mizar_Z7020_2018.3/Part4_Linux_Demo/10_petalinux_hdmi_wifi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_smc_0/bd_0/ip/ip_8/bd_173e_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Mizar_Z7020_2018.3/Part4_Linux_Demo/10_petalinux_hdmi_wifi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_rst_ps7_0_140M_0/hdmi_out_rst_ps7_0_140M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Mizar_Z7020_2018.3/Part4_Linux_Demo/10_petalinux_hdmi_wifi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_rst_ps7_0_140M_0/hdmi_out_rst_ps7_0_140M_0.xdc]
set_property used_in_implementation false [get_files -all d:/Mizar_Z7020_2018.3/Part4_Linux_Demo/10_petalinux_hdmi_wifi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_rst_ps7_0_140M_0/hdmi_out_rst_ps7_0_140M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Mizar_Z7020_2018.3/Part4_Linux_Demo/10_petalinux_hdmi_wifi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_xbar_0/hdmi_out_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Mizar_Z7020_2018.3/Part4_Linux_Demo/10_petalinux_hdmi_wifi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_rst_ps7_0_100M_0/hdmi_out_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Mizar_Z7020_2018.3/Part4_Linux_Demo/10_petalinux_hdmi_wifi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_rst_ps7_0_100M_0/hdmi_out_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/Mizar_Z7020_2018.3/Part4_Linux_Demo/10_petalinux_hdmi_wifi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_rst_ps7_0_100M_0/hdmi_out_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Mizar_Z7020_2018.3/Part4_Linux_Demo/10_petalinux_hdmi_wifi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_v_axi4s_vid_out_0_0/hdmi_out_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Mizar_Z7020_2018.3/Part4_Linux_Demo/10_petalinux_hdmi_wifi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_v_axi4s_vid_out_0_0/hdmi_out_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Mizar_Z7020_2018.3/Part4_Linux_Demo/10_petalinux_hdmi_wifi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_v_tc_0_0/hdmi_out_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Mizar_Z7020_2018.3/Part4_Linux_Demo/10_petalinux_hdmi_wifi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_v_tc_0_0/hdmi_out_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Mizar_Z7020_2018.3/Part4_Linux_Demo/10_petalinux_hdmi_wifi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_rgb2dvi_0_1/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all d:/Mizar_Z7020_2018.3/Part4_Linux_Demo/10_petalinux_hdmi_wifi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_rgb2dvi_0_1/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Mizar_Z7020_2018.3/Part4_Linux_Demo/10_petalinux_hdmi_wifi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_rgb2dvi_0_1/src/rgb2dvi_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Mizar_Z7020_2018.3/Part4_Linux_Demo/10_petalinux_hdmi_wifi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_auto_pc_0/hdmi_out_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/Mizar_Z7020_2018.3/Part4_Linux_Demo/10_petalinux_hdmi_wifi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/hdmi_out_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Mizar_Z7020_2018.3/Part4_Linux_Demo/10_petalinux_hdmi_wifi/petalinux_hdmi/petalinux_hdmi.srcs/constrs_1/new/hdmi_out.xdc
set_property used_in_implementation false [get_files D:/Mizar_Z7020_2018.3/Part4_Linux_Demo/10_petalinux_hdmi_wifi/petalinux_hdmi/petalinux_hdmi.srcs/constrs_1/new/hdmi_out.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top hdmi_out_wrapper -part xc7z020clg400-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef hdmi_out_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file hdmi_out_wrapper_utilization_synth.rpt -pb hdmi_out_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
