# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_rst_ps7_0_100M_0/hdmi_out_rst_ps7_0_100M_0.xci
# IP: The module: 'hdmi_out_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_rst_ps7_0_100M_0/hdmi_out_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_out_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_rst_ps7_0_100M_0/hdmi_out_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_out_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_rst_ps7_0_100M_0/hdmi_out_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_out_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_rst_ps7_0_100M_0/hdmi_out_rst_ps7_0_100M_0.xci
# IP: The module: 'hdmi_out_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_rst_ps7_0_100M_0/hdmi_out_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_out_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_rst_ps7_0_100M_0/hdmi_out_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_out_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/ZYNQ_Mizar-7020/06_Linux_Demo/5_petalinux_hdmi/petalinux_hdmi/petalinux_hdmi.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_rst_ps7_0_100M_0/hdmi_out_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_out_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
